[package]
name = "vista_protocol"
version = "0.1.0"
edition = "2021"
description = "Vista Protocol — attention monetization core program"

[lib]
crate-type = ["cdylib", "lib"]
name = "vista_protocol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
