/**
 * End-to-end integration script.
 *
 * Idempotent: persists generated keypairs and the mock USDC mint to
 * `scripts/.devnet-e2e-keypairs/`. First run bootstraps everything; subsequent
 * runs reuse the same actors, top up SOL/USDC only if needed, skip already-
 * initialized PDAs, and run a fresh campaign+session+aggregation cycle.
 *
 *   anchor build
 *   anchor deploy
 *   ANCHOR_PROVIDER_URL=https://api.devnet.solana.com \
 *   ANCHOR_WALLET=~/.config/solana/id.json \
 *     npx ts-node scripts/devnet-e2e.ts
 *
 * To force a clean slate (e.g. after redeploying programs to new IDs), delete
 * `scripts/.devnet-e2e-keypairs/` and re-run.
 */

import * as anchor from "@coral-xyz/anchor";
import { BN } from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  sendAndConfirmTransaction,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
  Transaction,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  getAccount,
  getOrCreateAssociatedTokenAccount,
  mintTo,
} from "@solana/spl-token";
import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";

import type { VistaProtocol } from "../target/types/vista_protocol";
import type { OracleRegistry } from "../target/types/oracle_registry";
import type { AttentionAggregator } from "../target/types/attention_aggregator";

// ── Persistence helpers ────────────────────────────────────────────────────

const STATE_DIR = path.resolve(__dirname, ".devnet-e2e-keypairs");
const STATE_FILE = path.join(STATE_DIR, "state.json");

interface PersistedState {
  mint: string;
}

function ensureStateDir() {
  if (!fs.existsSync(STATE_DIR)) {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(
      path.join(STATE_DIR, ".gitignore"),
      "# Generated by devnet-e2e.ts; safe to delete to start over.\n*\n",
    );
  }
}

function loadOrCreateKeypair(name: string): { kp: Keypair; created: boolean } {
  ensureStateDir();
  const file = path.join(STATE_DIR, `${name}.json`);
  if (fs.existsSync(file)) {
    const bytes = JSON.parse(fs.readFileSync(file, "utf-8")) as number[];
    return { kp: Keypair.fromSecretKey(Uint8Array.from(bytes)), created: false };
  }
  const kp = Keypair.generate();
  fs.writeFileSync(file, JSON.stringify(Array.from(kp.secretKey)));
  return { kp, created: true };
}

function loadState(): PersistedState | null {
  if (!fs.existsSync(STATE_FILE)) return null;
  return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
}

function saveState(state: PersistedState) {
  ensureStateDir();
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

async function accountExists(
  connection: Connection,
  pubkey: PublicKey,
): Promise<boolean> {
  const info = await connection.getAccountInfo(pubkey, "confirmed");
  return info !== null;
}

async function topUpSolIfBelow(
  connection: Connection,
  admin: Keypair,
  fundees: { kp: Keypair; label: string }[],
  thresholdLamports: number,
  fundAmountLamports: number,
): Promise<void> {
  const ixs: Array<{
    ix: anchor.web3.TransactionInstruction;
    label: string;
    topUp: number;
  }> = [];
  for (const { kp, label } of fundees) {
    const bal = await connection.getBalance(kp.publicKey, "confirmed");
    if (bal < thresholdLamports) {
      ixs.push({
        ix: SystemProgram.transfer({
          fromPubkey: admin.publicKey,
          toPubkey: kp.publicKey,
          lamports: fundAmountLamports - bal,
        }),
        label,
        topUp: (fundAmountLamports - bal) / LAMPORTS_PER_SOL,
      });
    }
  }
  if (ixs.length === 0) {
    console.log("  all keypairs already funded above threshold");
    return;
  }

  const adminBal = await connection.getBalance(admin.publicKey);
  const total = ixs.reduce((sum, x) => sum + x.topUp * LAMPORTS_PER_SOL, 0);
  if (adminBal < total + 0.02 * LAMPORTS_PER_SOL) {
    throw new Error(
      `Admin ${admin.publicKey.toString()} has ${adminBal / LAMPORTS_PER_SOL} SOL; ` +
        `need ${(total + 0.02 * LAMPORTS_PER_SOL) / LAMPORTS_PER_SOL} for top-ups. ` +
        `Refill via https://faucet.solana.com.`,
    );
  }

  const tx = new Transaction().add(...ixs.map((x) => x.ix));
  await sendAndConfirmTransaction(connection, tx, [admin], {
    commitment: "confirmed",
  });
  for (const x of ixs) {
    console.log(`  topped up ${x.label} with ${x.topUp.toFixed(3)} SOL`);
  }
}

async function topUpUsdcIfBelow(
  connection: Connection,
  admin: Keypair,
  mint: PublicKey,
  ata: PublicKey,
  label: string,
  thresholdAtoms: bigint,
  topUpAtoms: bigint,
): Promise<void> {
  const acc = await getAccount(connection, ata);
  if (acc.amount >= thresholdAtoms) return;
  await mintTo(connection, admin, mint, ata, admin, topUpAtoms);
  console.log(
    `  minted ${Number(topUpAtoms) / 1e6} USDC to ${label} (ATA balance was ${Number(acc.amount) / 1e6})`,
  );
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const vista = anchor.workspace.VistaProtocol as anchor.Program<VistaProtocol>;
  const registry = anchor.workspace
    .OracleRegistry as anchor.Program<OracleRegistry>;
  const aggregator = anchor.workspace
    .AttentionAggregator as anchor.Program<AttentionAggregator>;

  const connection = provider.connection;
  const admin = (provider.wallet as anchor.Wallet).payer;

  console.log("vista_protocol      ", vista.programId.toString());
  console.log("oracle_registry     ", registry.programId.toString());
  console.log("attention_aggregator", aggregator.programId.toString());
  console.log("admin               ", admin.publicKey.toString());
  console.log("");

  // ── 1. Load or create persistent actors ─────────────────────────────
  console.log("── 1. Loading persistent actors");
  const advertiser = loadOrCreateKeypair("advertiser");
  const userWallet = loadOrCreateKeypair("user_wallet");
  const publisherWallet = loadOrCreateKeypair("publisher_wallet");
  const vistaWallet = loadOrCreateKeypair("vista_wallet");
  const oracle1 = loadOrCreateKeypair("oracle_1");
  const oracle2 = loadOrCreateKeypair("oracle_2");
  const oracle3 = loadOrCreateKeypair("oracle_3");
  const oracles = [oracle1.kp, oracle2.kp, oracle3.kp];
  const oracleSigner = oracle1.kp; // also doubles as tick caller

  for (const [label, entry] of Object.entries({
    advertiser,
    user_wallet: userWallet,
    publisher_wallet: publisherWallet,
    vista_wallet: vistaWallet,
    oracle_1: oracle1,
    oracle_2: oracle2,
    oracle_3: oracle3,
  })) {
    console.log(
      `  ${label.padEnd(18)} ${entry.kp.publicKey.toString()} ${entry.created ? "(NEW)" : ""}`,
    );
  }

  // ── 2. Top up SOL where needed (only signing keypairs) ──────────────
  console.log("\n── 2. Topping up SOL");
  const SOL_THRESHOLD = 0.04 * LAMPORTS_PER_SOL;
  const SOL_TARGET = 0.08 * LAMPORTS_PER_SOL;
  await topUpSolIfBelow(
    connection,
    admin,
    [
      { kp: advertiser.kp, label: "advertiser" },
      { kp: oracle1.kp, label: "oracle_1" },
      { kp: oracle2.kp, label: "oracle_2" },
      { kp: oracle3.kp, label: "oracle_3" },
    ],
    SOL_THRESHOLD,
    SOL_TARGET,
  );

  // ── 3. Load or create mock USDC mint ────────────────────────────────
  console.log("\n── 3. Mock USDC mint");
  let usdcMint: PublicKey;
  const persisted = loadState();
  if (persisted?.mint) {
    usdcMint = new PublicKey(persisted.mint);
    const exists = await accountExists(connection, usdcMint);
    if (!exists) {
      console.log(
        `  warning: persisted mint ${usdcMint.toString()} not found on chain — creating fresh`,
      );
      usdcMint = await createMint(connection, admin, admin.publicKey, null, 6);
      saveState({ mint: usdcMint.toString() });
    } else {
      console.log(`  reusing ${usdcMint.toString()}`);
    }
  } else {
    usdcMint = await createMint(connection, admin, admin.publicKey, null, 6);
    saveState({ mint: usdcMint.toString() });
    console.log(`  created ${usdcMint.toString()}`);
  }

  // ── 4. ATAs (idempotent via getOrCreate) + USDC top-ups ─────────────
  console.log("\n── 4. ATAs + USDC top-ups");
  const advertiserAta = (
    await getOrCreateAssociatedTokenAccount(
      connection,
      admin, // admin pays for ATA creation rent (cheaper than draining advertiser SOL)
      usdcMint,
      advertiser.kp.publicKey,
    )
  ).address;
  const vistaAta = (
    await getOrCreateAssociatedTokenAccount(
      connection,
      admin,
      usdcMint,
      vistaWallet.kp.publicKey,
    )
  ).address;
  const oracleAtas: PublicKey[] = [];
  for (const o of oracles) {
    const ata = (
      await getOrCreateAssociatedTokenAccount(
        connection,
        admin,
        usdcMint,
        o.publicKey,
      )
    ).address;
    oracleAtas.push(ata);
  }

  // Top up advertiser to >= 50 USDC (campaign budget = 10 USDC)
  await topUpUsdcIfBelow(
    connection,
    admin,
    usdcMint,
    advertiserAta,
    "advertiser",
    50_000_000n, // threshold 50 USDC
    100_000_000n, // top up 100 USDC
  );
  // Top up each oracle to >= 150 USDC (need 100 for stake + buffer for re-stake on fresh deploys)
  for (let i = 0; i < oracles.length; i++) {
    await topUpUsdcIfBelow(
      connection,
      admin,
      usdcMint,
      oracleAtas[i],
      `oracle_${i + 1}`,
      150_000_000n, // threshold 150 USDC
      200_000_000n, // top up 200 USDC
    );
  }

  // ── 5. Initialize vista_protocol (idempotent) ───────────────────────
  console.log("\n── 5. vista_protocol initialize");
  const [configPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("config")],
    vista.programId,
  );
  const [vaultAuthority] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault_authority")],
    vista.programId,
  );
  const [userVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("user_vault")],
    vista.programId,
  );
  const [receiptCounter] = PublicKey.findProgramAddressSync(
    [Buffer.from("receipt_counter")],
    vista.programId,
  );

  if (await accountExists(connection, configPda)) {
    console.log("  Config exists — skipping initialize");
  } else {
    await vista.methods
      .initialize(oracleSigner.publicKey, vistaWallet.kp.publicKey)
      .accountsPartial({
        admin: admin.publicKey,
        config: configPda,
        usdcMint,
        vaultAuthority,
        userVault,
        receiptCounter,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .rpc();
    console.log("  initialized");
  }

  // ── 6. Initialize oracle_registry (idempotent) ──────────────────────
  console.log("\n── 6. oracle_registry initialize");
  const [registryPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("registry")],
    registry.programId,
  );
  const [stakeAuth] = PublicKey.findProgramAddressSync(
    [Buffer.from("stake_authority")],
    registry.programId,
  );
  const [stakeVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("stake_vault")],
    registry.programId,
  );
  const [rewardAuth] = PublicKey.findProgramAddressSync(
    [Buffer.from("reward_authority")],
    registry.programId,
  );
  const [rewardVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("reward_vault")],
    registry.programId,
  );

  if (await accountExists(connection, registryPda)) {
    console.log("  Registry exists — skipping initialize");
  } else {
    await registry.methods
      .initialize(aggregator.programId, new BN(100_000_000), 1000)
      .accountsPartial({
        admin: admin.publicKey,
        registry: registryPda,
        usdcMint,
        stakeAuthority: stakeAuth,
        stakeVault,
        rewardAuthority: rewardAuth,
        rewardVault,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .rpc();
    console.log("  initialized");
  }

  // Register oracles (idempotent)
  console.log("  registering oracles…");
  const oracleNodes: PublicKey[] = [];
  for (let i = 0; i < oracles.length; i++) {
    const [nodePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("oracle_node"), oracles[i].publicKey.toBuffer()],
      registry.programId,
    );
    oracleNodes.push(nodePda);
    if (await accountExists(connection, nodePda)) {
      console.log(`    oracle_${i + 1}: already registered`);
      continue;
    }
    await registry.methods
      .registerOracle(new BN(100_000_000), `https://oracle-${i + 1}.demo`)
      .accountsPartial({
        oracle: oracles[i].publicKey,
        registry: registryPda,
        oracleNode: nodePda,
        oracleToken: oracleAtas[i],
        stakeVault,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([oracles[i]])
      .rpc();
    console.log(`    oracle_${i + 1}: registered with 100 USDC stake`);
  }

  // ── 7. Initialize attention_aggregator (idempotent) ─────────────────
  console.log("\n── 7. attention_aggregator initialize");
  const [aggCfg] = PublicKey.findProgramAddressSync(
    [Buffer.from("aggregator_config")],
    aggregator.programId,
  );
  const [aggSigner] = PublicKey.findProgramAddressSync(
    [Buffer.from("aggregator_signer")],
    aggregator.programId,
  );

  if (await accountExists(connection, aggCfg)) {
    console.log("  AggregatorConfig exists — skipping initialize");
  } else {
    await aggregator.methods
      .initialize(vista.programId, registry.programId, 3, 2000, new BN(10))
      .accountsPartial({
        admin: admin.publicKey,
        config: aggCfg,
        aggregatorSigner: aggSigner,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .rpc();
    console.log("  initialized");
  }

  // ── 8. Fresh campaign + session per run ─────────────────────────────
  console.log("\n── 8. Fresh campaign + session");
  const campaignId = crypto.randomBytes(32);
  const sessionId = crypto.randomBytes(32);
  console.log("  campaign_id:", campaignId.toString("hex"));
  console.log("  session_id :", sessionId.toString("hex"));

  const [campaignPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("campaign"), campaignId],
    vista.programId,
  );
  const [campaignVaultAuth] = PublicKey.findProgramAddressSync(
    [Buffer.from("campaign_vault_authority"), campaignId],
    vista.programId,
  );
  const [campaignVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("campaign_vault"), campaignId],
    vista.programId,
  );

  await vista.methods
    .depositCampaign(
      Array.from(campaignId),
      new BN(10_000_000),
      new BN(100_000),
      new BN(60),
    )
    .accountsPartial({
      advertiser: advertiser.kp.publicKey,
      config: configPda,
      campaign: campaignPda,
      campaignVaultAuthority: campaignVaultAuth,
      campaignVault,
      advertiserToken: advertiserAta,
      usdcMint,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([advertiser.kp])
    .rpc();

  const [sessionPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("session"), sessionId],
    vista.programId,
  );
  const [validatorPoolAuth] = PublicKey.findProgramAddressSync(
    [Buffer.from("validator_pool_authority"), sessionId],
    vista.programId,
  );
  const [validatorPoolVault] = PublicKey.findProgramAddressSync(
    [Buffer.from("validator_pool"), sessionId],
    vista.programId,
  );

  await vista.methods
    .startStream(Array.from(sessionId), Array.from(campaignId))
    .accountsPartial({
      oracle: oracleSigner.publicKey,
      config: configPda,
      campaign: campaignPda,
      session: sessionPda,
      userWallet: userWallet.kp.publicKey,
      publisherWallet: publisherWallet.kp.publicKey,
      validatorPoolAuthority: validatorPoolAuth,
      validatorPoolVault,
      usdcMint,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([oracleSigner])
    .rpc();

  const [userBal] = PublicKey.findProgramAddressSync(
    [Buffer.from("balance"), userWallet.kp.publicKey.toBuffer()],
    vista.programId,
  );
  const [publisherBal] = PublicKey.findProgramAddressSync(
    [Buffer.from("balance"), publisherWallet.kp.publicKey.toBuffer()],
    vista.programId,
  );

  await vista.methods
    .tickStream(new BN(15))
    .accountsPartial({
      oracle: oracleSigner.publicKey,
      config: configPda,
      session: sessionPda,
      campaign: campaignPda,
      campaignVaultAuthority: campaignVaultAuth,
      campaignVault,
      userVault,
      vaultAuthority,
      vistaWalletToken: vistaAta,
      validatorPoolVault,
      userBalance: userBal,
      publisherBalance: publisherBal,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([oracleSigner])
    .rpc();

  const poolAfterTick = await getAccount(connection, validatorPoolVault);
  console.log(
    `  validator pool after tick: ${poolAfterTick.amount} (expected 150000)`,
  );

  // ── 9. Oracles submit verifications ─────────────────────────────────
  console.log("\n── 9. Oracle submissions (80, 80, 40)");
  const [aggSessionPda] = PublicKey.findProgramAddressSync(
    [Buffer.from("attention_session"), sessionId],
    aggregator.programId,
  );

  const scores = [80, 80, 40];
  for (let i = 0; i < oracles.length; i++) {
    await aggregator.methods
      .submitVerification(Array.from(sessionId), scores[i])
      .accountsPartial({
        oracle: oracles[i].publicKey,
        config: aggCfg,
        oracleNode: oracleNodes[i],
        attentionSession: aggSessionPda,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([oracles[i]])
      .rpc();
  }

  // ── 10. Aggregate ────────────────────────────────────────────────────
  console.log("\n── 10. aggregate_results");
  const rewardVaultBefore = await getAccount(connection, rewardVault);
  await aggregator.methods
    .aggregateResults(Array.from(sessionId))
    .accountsPartial({
      config: aggCfg,
      aggregatorSigner: aggSigner,
      attentionSession: aggSessionPda,
      oracleRegistryProgram: registry.programId,
      registry: registryPda,
      vistaProtocolProgram: vista.programId,
      validatorPoolVault,
      validatorPoolAuthority: validatorPoolAuth,
      rewardVault,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .remainingAccounts(
      oracleNodes.map((n) => ({ pubkey: n, isWritable: true, isSigner: false })),
    )
    .rpc();

  // ── 11. Assertions ───────────────────────────────────────────────────
  console.log("\n── 11. Result");
  const session = await aggregator.account.attentionSession.fetch(aggSessionPda);
  console.log(`  consensus_score   = ${session.consensusScore}`);
  console.log(`  consensus_reached = ${session.consensusReached}`);
  console.log(`  is_settled        = ${session.isSettled}`);

  const poolAfter = await getAccount(connection, validatorPoolVault);
  console.log(`  validator pool after aggregate: ${poolAfter.amount}`);

  const rewardAfter = await getAccount(connection, rewardVault);
  const rewardDelta = rewardAfter.amount - rewardVaultBefore.amount;
  console.log(
    `  reward vault: ${rewardAfter.amount} (delta this run: +${rewardDelta})`,
  );

  for (let i = 0; i < oracles.length; i++) {
    const node = await registry.account.oracleNode.fetch(oracleNodes[i]);
    console.log(
      `  oracle_${i + 1}: stake=${node.stake} reward=${node.rewardBalance} slashes=${node.totalSlashes}`,
    );
  }

  if (poolAfter.amount !== 0n) {
    throw new Error("validator pool not fully drained");
  }
  if (rewardDelta !== 150000n) {
    throw new Error(
      `reward vault delta ${rewardDelta} !== 150000 (10% of 1.5M tick)`,
    );
  }
  console.log("\n✅ devnet-e2e: trustless attention market working end-to-end.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
